# Generated by Django 4.1.7 on 2023-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='User URL')),
                ('key', models.CharField(max_length=6, verbose_name='Access Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('clicks', models.PositiveBigIntegerField(verbose_name='Clicks Count')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
